### ISSUE TITLE
module 'yaml' has no attribute 'FullLoader'

### ISSUE THREAD

**Issue by Jiadalee** [kLabUM/pystorms#4]
I got an error when I'm testing the example. Seems like the yaml,py should be renamed?https://stackoverflow.com/questions/9286637/pyyaml-error-attribute-error-no-attribute-load

![image](https://user-images.githubusercontent.com/30839207/78602334-e767a180-781b-11ea-955a-44f3c151ca67.png)

**Comment by abhiramm7** [comment]
Hi Jiada, 

It seems that `yaml.FullLoader` seems to be part of the PyYAML (https://pyyaml.org/wiki/PyYAML#history) 5.1 or greater. Can you verify the version you have on your end. Thanks for pointing this out, I will update the requirements to indicate the specific versions.

**Comment by Jiadalee** [comment]
Hi Abhi,

The PyYAML version is 5.3.1 but the yaml version is 3.1.3 in my side.

**Comment by abhiramm7** [comment]
Issue seems to be similar to https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader. Can you try it and let me know if it helps?

**Comment by Jiadalee** [comment]
@abhiramm7 It works now. Thank you very much!
