### ISSUE TITLE
Question for 'Theta' case

### ISSUE THREAD

**Issue by Jiadalee** [kLabUM/pystorms#7]
What does the variable 'potential' represent in the example codes of Theta case below? If the 'state' is the controller action, why did you make the 'state' over 'Max' to get the 'fd'?

`def controller(state, target, MAX=2.0):
    fd = state / MAX
    avg_fd = np.mean(fd)
    potential = fd - avg_fd  # [<0, 0, <1]

    for i in range(0, 2):
        if potential[i] < -0.001:
            potential[i] = 0.0
        elif potential[i] < 0.001 and potential[i] > -0.001:
            potential[i] = avg_fd

    if sum(potential) > 0.0:
        potential = potential / sum(potential)

    actions = np.zeros(2)
    if state[0] > 0.00:
        flow0 = target * potential[0]
        actions[0] = min(1.0, flow0 / (1.00 * np.sqrt(2.0 * 9.81 * state[0])))
    if state[1] > 0.00:
        flow1 = target * potential[1]
        actions[1] = min(1.0, flow1 / (1.00 * np.sqrt(2.0 * 9.81 * state[1])))
    return actions`

**Comment by abhiramm7** [comment]
Think of filling degree (`fd`) as the utilized storage in a controlled basin. Potential in a basin represents the difference between `fd` in the basin and the `fd` of the network (represented by mean).  This difference informs us the amount of utilization in each basin relative to the network. This relative utilization of storage in each basin is then used to take the control actions. 

I am not sure what you mean by "If the 'state' is the controller action", can you elaborate on it. 

`fd` is defined as the normalized storage utilization in a basin. In this scenario, basins are rectangular, hence the normalization can be expressed in terms of depth rather than volume. Max represents the maximum depth in each basin, so `fd` becomes state (which is the depth in the basin) divided by Max.

Hope this helps.

**Comment by Jiadalee** [comment]
@abhiramm7 Thanks for the explanation. I personally assumed 'state' is the 'controller action'.  I think it would be more intuitive by adding some notes beside the codes. To maintain the flow below 0.5, these equations look a little complicated. Is there any simple way to achieve this? For instance, creating an outflow variable as 'state', and making a loop as:
`if state> 0.5:
    actions >= 0.8`
In this case, when the outflow is over 0.5, the gate will open 80% or bigger.  I'm not sure if this works. How do you think about it?

**Comment by abhiramm7** [comment]
This example demonstrates the use of equal-filling control approach for maintaining flows at the outlet. This is an approach for controlling flows, there are other ways you can go about controlling network for achieving flow control objectives. You can definitely have a controller that reacts to the flows and changes the gates to a pre-defined position. But personally, I would prefer an approach were the user would not have to make those choice and it is unto the controller to figure what those gate position would be. 

The equation in the example is the flow though orifice equation, 

![Q = Valve \times Area \times \sqrt{2 \times g \times depth}](https://render.githubusercontent.com/render/math?math=Q%20%3D%20Valve%20%5Ctimes%20Area%20%5Ctimes%20%5Csqrt%7B2%20%5Ctimes%20g%20%5Ctimes%20depth%7D)

and valve position for each basin is computed by, 

![\frac{Q}{Area \times \sqrt{2 \times g \times depth}} = Valve  ](https://render.githubusercontent.com/render/math?math=%5Cfrac%7BQ%7D%7BArea%20%5Ctimes%20%5Csqrt%7B2%20%5Ctimes%20g%20%5Ctimes%20depth%7D%7D%20%3D%20Valve%20%20)

The outflows that have to be achieved from each basin are estimated from the filling degree and potential

![Q_{basin} = 0.5 \times \frac{\text{potential}_{basin}}{\sum \text{potential}}](https://render.githubusercontent.com/render/math?math=Q_%7Bbasin%7D%20%3D%200.5%20%5Ctimes%20%5Cfrac%7B%5Ctext%7Bpotential%7D_%7Bbasin%7D%7D%7B%5Csum%20%5Ctext%7Bpotential%7D%7D)

Thanks for pointing it out, I'll add more comments in the documentation to make this more explicit.

**Comment by abhiramm7** [comment]
@Jiadalee I am closing this issue for now. Let me know if you need any additional clarifications.
